// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Arrow: typeof import('./src/components/icons/Arrow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    ZoomIcon: typeof import('./src/components/icons/ZoomIcon.vue')['default']
    ZoomInIcon: typeof import('./src/components/icons/ZoomInIcon.vue')['default']
    ZoonOutIcon: typeof import('./src/components/icons/ZoonOutIcon.vue')['default']
  }
}
